"""Application services."""

from jobpilot.services.application_queue_service import (
    SOURCE_LABELS,
    TIER_ADJUSTMENTS,
    ApplicationQueueService,
    build_queue_item,
    calculate_preparation_status,
    calculate_priority_score,
    normalize_source,
    queue_tier,
    safe_external_url,
    sort_queue_items,
)

from jobpilot.services.batch_job_input_parser import (
    MAX_BATCH_JOBS,
    MIN_BATCH_JOBS,
    BatchInputError,
    BatchJobCountError,
    EmptyBatchJobError,
    parse_batch_job_input,
)
from jobpilot.services.batch_apply_service import (
    EXCLUDED_APPLICATION_STATUSES,
    BatchApplyService,
    apply_item_identity,
    calculate_apply_readiness,
    default_selected,
    infer_job_source,
    screening_result_fingerprint,
    valid_source_url,
)
from jobpilot.services.batch_apply_execution_service import (
    MAX_EXECUTION_JOBS,
    BatchApplyExecutionService,
    create_safe_handoff_execution,
)
from jobpilot.services.batch_screening_service import (
    CAUTION_SCORE_MIN,
    MAX_PRIORITY_REQUIRED_GAPS,
    MAX_RECOMMENDED_REQUIRED_GAPS,
    PRIORITY_SCORE_MIN,
    RECOMMENDED_SCORE_MIN,
    BatchScreeningService,
    CandidateProfileRequiredError,
    batch_fingerprint,
    batch_item_cache_key,
    build_batch_screening_result,
    build_completed_screening_item,
    build_screening_reason,
    calculate_screening_tier,
    save_batch_item,
    save_priority_items,
    sort_batch_items,
)

from jobpilot.services.job_search_analytics import (
    HIGH_MATCH_MIN_SCORE,
    MEDIUM_MATCH_MIN_SCORE,
    MIN_APPLICATIONS_FOR_TRENDS,
    MIN_MATCH_RESULTS_FOR_SKILL_INSIGHTS,
    TOP_MATCHING_JOBS_LIMIT,
    JobSearchAnalyticsService,
)
from jobpilot.services.fast_screening_service import (
    FAST_SCREENING_TEMPERATURE,
    FAST_SCREENING_THINKING,
    FastScreeningService,
    candidate_fast_screening_summary,
)
from jobpilot.services.fast_screening_pipeline import (
    FastScreeningPipeline,
    fast_screening_cache_key,
    should_run_pro,
)
from jobpilot.services.local_pre_screen import LocalPreScreenService
from jobpilot.services.screening_preparation import (
    MAX_TRIMMED_JD_CHARACTERS,
    build_compact_candidate_summary,
    build_compact_candidate_profile,
    trim_job_description,
)

from jobpilot.services.job_analyzer import (
    MAX_JOB_DESCRIPTION_CHARACTERS,
    MIN_JOB_DESCRIPTION_CHARACTERS,
    EmptyJobDescriptionError,
    JobAnalyzer,
    JobDescriptionValidationError,
    LongJobDescriptionError,
    ShortJobDescriptionError,
    ensure_job_profile_has_core_data,
    job_profile_core_field_count,
    normalize_job_description,
    validate_job_description,
)
from jobpilot.services.matching_score import (
    DIMENSION_WEIGHTS,
    calculate_education_other_score,
    calculate_overall_score,
    calculate_relevance_score,
    calculate_score_breakdown,
    calculate_skill_score,
)
from jobpilot.services.matching_service import (
    MatchingService,
    candidate_skill_evidence,
    normalize_skill,
)
from jobpilot.services.resume_analyzer import (
    ResumeAnalyzer,
    candidate_profile_core_field_count,
    ensure_candidate_profile_has_core_data,
)
from jobpilot.services.resume_optimization_service import (
    MAX_KEEP_SUGGESTIONS,
    MAX_SUGGESTIONS_PER_CHANGE_DECISION,
    ResumeOptimizationService,
    normalize_optimization_result,
)

__all__ = [
    "BatchInputError",
    "BatchApplyService",
    "BatchApplyExecutionService",
    "BatchJobCountError",
    "BatchScreeningService",
    "CandidateProfileRequiredError",
    "EmptyBatchJobError",
    "EmptyJobDescriptionError",
    "JobAnalyzer",
    "FastScreeningPipeline",
    "FastScreeningService",
    "LocalPreScreenService",
    "MAX_TRIMMED_JD_CHARACTERS",
    "JobSearchAnalyticsService",
    "JobDescriptionValidationError",
    "LongJobDescriptionError",
    "MAX_BATCH_JOBS",
    "MAX_EXECUTION_JOBS",
    "create_safe_handoff_execution",
    "MAX_PRIORITY_REQUIRED_GAPS",
    "MAX_RECOMMENDED_REQUIRED_GAPS",
    "MatchingService",
    "MAX_JOB_DESCRIPTION_CHARACTERS",
    "MAX_KEEP_SUGGESTIONS",
    "MAX_SUGGESTIONS_PER_CHANGE_DECISION",
    "MIN_JOB_DESCRIPTION_CHARACTERS",
    "MIN_BATCH_JOBS",
    "MIN_APPLICATIONS_FOR_TRENDS",
    "MIN_MATCH_RESULTS_FOR_SKILL_INSIGHTS",
    "HIGH_MATCH_MIN_SCORE",
    "MEDIUM_MATCH_MIN_SCORE",
    "ResumeAnalyzer",
    "ResumeOptimizationService",
    "ShortJobDescriptionError",
    "TOP_MATCHING_JOBS_LIMIT",
    "PRIORITY_SCORE_MIN",
    "RECOMMENDED_SCORE_MIN",
    "CAUTION_SCORE_MIN",
    "DIMENSION_WEIGHTS",
    "calculate_education_other_score",
    "calculate_overall_score",
    "calculate_relevance_score",
    "calculate_score_breakdown",
    "calculate_skill_score",
    "calculate_screening_tier",
    "calculate_apply_readiness",
    "apply_item_identity",
    "default_selected",
    "infer_job_source",
    "screening_result_fingerprint",
    "valid_source_url",
    "EXCLUDED_APPLICATION_STATUSES",
    "candidate_fast_screening_summary",
    "build_compact_candidate_summary",
    "build_compact_candidate_profile",
    "trim_job_description",
    "fast_screening_cache_key",
    "should_run_pro",
    "FAST_SCREENING_TEMPERATURE",
    "FAST_SCREENING_THINKING",
    "build_screening_reason",
    "build_batch_screening_result",
    "build_completed_screening_item",
    "batch_fingerprint",
    "batch_item_cache_key",
    "candidate_profile_core_field_count",
    "ensure_candidate_profile_has_core_data",
    "ensure_job_profile_has_core_data",
    "job_profile_core_field_count",
    "candidate_skill_evidence",
    "normalize_skill",
    "normalize_job_description",
    "normalize_optimization_result",
    "parse_batch_job_input",
    "save_batch_item",
    "save_priority_items",
    "sort_batch_items",
    "validate_job_description",
    "ApplicationQueueService",
    "SOURCE_LABELS",
    "TIER_ADJUSTMENTS",
    "build_queue_item",
    "calculate_preparation_status",
    "calculate_priority_score",
    "normalize_source",
    "queue_tier",
    "safe_external_url",
    "sort_queue_items",
]
